main: "cc.dreamcode.plugingencashhoe.GenCashHoePlugin"
version: "1.0-InDEV"
name: "Dream-GenCashHoe"
description: "Dream-GenCashHoe plugin written by dreamcode.cc"
website: "https://dreamcode.cc"
author: "n4a_"
api-version: 1.13
softdepend:
  - Vault